### ISSUE TITLE
Set up the development environment

### ISSUE THREAD

**Issue by jungcome7** [jungcome7/WeAreTheWorld#1]
### 개발 환경 설정
- Prettier 설정
- Eslint 설정
- React관련 패키지 설치(react, styled-components 등 )
- Redux 및 Redux 미들웨어 패키지 설치(redux, react-redux, redux-saga 등)

**Comment by doonguk** [comment]
![image](https://user-images.githubusercontent.com/39187116/101478913-b932f680-3994-11eb-8b6f-ee71265d12a4.png)

**Comment by jungcome7** [comment]
![image](https://user-images.githubusercontent.com/34447105/101557339-2c258700-3a00-11eb-947a-36743a0dc591.png)
